### ISSUE TITLE
Broken link for office add-ins model

### ISSUE THREAD

**Issue by mohamed-azhar** [OfficeDev/open-xml-docs#136]
Page: [Getting started with the Open XML SDK 2.5 for Office](https://docs.microsoft.com/en-us/office/open-xml/getting-started)
Issue: Broken link inside the **Note**
Broken link: [Office Add-ins model](https://docs.microsoft.com/en-us/office/dev/add-ins/overview/office-add-ins.md)

Recommended link for replacement: [Office Add-ins platform overview](https://docs.microsoft.com/en-us/office/dev/add-ins/overview/office-add-ins)

**Comment by lindalu-MSFT** [comment]
Thanks for finding this! It was broken in one of the include files so it was likely broken a bunch of places. I just fixed and it should be live shortly.
