### ISSUE TITLE
Get cell value bug

### ISSUE THREAD

**Issue by Asbjoedt** [OfficeDev/open-xml-docs#144]
This document:

https://github.com/OfficeDev/open-xml-docs/blob/live/docs/how-to-retrieve-the-values-of-cells-in-a-spreadsheet.md

Has this issue:

On this code:
if (theCell.InnerText.Length > 0)

It throws exception:
System.NullReferenceException: 'Object reference not set to an instance of an object.'

The exception happens when you want to find value of any cell in row A, if row A has been formatted to be a table, which means cells in row A will have name Column1, Column2 etc. and they will be filtering and sorting options.

**Comment by tomjebo** [comment]
@Asbjoedt what version of the Open XML SDK are you using?

**Comment by mikeebowen** [comment]
@Asbjoedt , does #296 resolve this?

**Comment by Asbjoedt** [comment]
@mikeebowen 
Thanks for taking the time to fix this.
I won't be checking if the bug is fixed, I will trust you on this one.
