### ISSUE TITLE
Sample code for inserting charts into spreadsheet is not working

### ISSUE THREAD

**Issue by Rohan-git-hub** [OfficeDev/open-xml-docs#146]
It edits the file and when I open the file it shows 
![image](https://user-images.githubusercontent.com/59329958/184858638-0a056350-7583-4b3d-8005-67de450706f4.png)

The sample code(for C#) was provided here :- https://docs.microsoft.com/en-us/office/open-xml/how-to-insert-a-chart-into-a-spreadsheet

**Comment by tomjebo** [comment]
@Rohan-git-hub, can you provide the version of the Open XML SDK that you're targeting?

**Comment by tomjebo** [comment]
Just FYI, I tested the sample code with the latest SDK from github and with V2.5 and they both had that same behavior. We will have to create a new sample to demonstrate how to add the chart as it looks like this hasn't worked for a long time.

**Comment by Rohan-git-hub** [comment]
@tomjebo I am using Open XML SDK version 2.9.1

**Comment by Rohan-git-hub** [comment]
Hi @tomjebo any update on this and can you please share an alternate resource for the same.

**Comment by rank-p** [comment]
I'm running into the same issue. Is there any update or workaround or other resource on the internet that explains it correctly?

**Comment by archerofthemark** [comment]
I've managed to get the C# sample code working, simply by replacing the link in the C# example  
```
graphicFrame.Append(new Graphic(new GraphicData(new ChartReference()            { Id = drawingsPart.GetIdOfPart(chartPart) }) 
        { Uri = "https://schemas.openxmlformats.org/drawingml/2006/chart" }));
```
with 
```
graphicFrame.Append(new Graphic(new GraphicData(new ChartReference()            { Id = drawingsPart.GetIdOfPart(chartPart) }) 
        { Uri = "http://schemas.openxmlformats.org/drawingml/2006/chart" }));
```

Hopefully this helps.

**Comment by tomjebo** [comment]
@archerofthemark Thanks for letting us know!

**Comment by mikeebowen** [comment]
closed by 

- #296
