### ISSUE TITLE
Can't read opened .docx document

### ISSUE THREAD

**Issue by TuTAH1** [OfficeDev/open-xml-docs#149]
I get "cannot access the file because it is being used by another process" exception when trying to `WordprocessingDocument.Open(filepath,false);`, **althrough I can open it in other programs** (like LibreOffice) in readonly mode.

**Comment by mikeebowen** [comment]
Hi @TuTAH1, sorry for the delayed response. This is a usage question that would be better asked on stackoverflow.con with the [openxml](https://stackoverflow.com/questions/tagged/openxml) or [openxml-sdk](https://stackoverflow.com/questions/tagged/openxml-sdk) tags.
