### ISSUE TITLE
 Update APIs for v3.0 when released

### ISSUE THREAD

**Issue by farzonl** [OfficeDev/open-xml-docs#156]
https://github.com/OfficeDev/open-xml-docs/blob/c354f7bd2ccdc74d50fa2e1295023dc91b37153b/docs/how-to-insert-a-comment-into-a-word-processing-document.md?plain=1#L99

GetPartsCountOfType has been removed from the sdk in the 3.0 beta. This example will need to be updated.

For more context see: https://github.com/dotnet/Open-XML-SDK/issues/1442

**Comment by twsouthwick** [comment]
The api refs are in a different repo, so adding a link here but we'll track it in this repo: https://github.com/OfficeDev/open-xml-docs-ref-dotnet

**Comment by twsouthwick** [comment]
This has been updated!
