### ISSUE TITLE
API xref syntax not supported?

### ISSUE THREAD

**Issue by twsouthwick** [OfficeDev/open-xml-docs#165]
@lindalu-MSFT Other docs projects I've worked in (asp.net and dotnet) allow for `<xref:...>` syntax to reference APIs to automatically resolve names and ensure it exists. I tried doing that here, but it doesn't seem to work. Is there a way to hook that up? Or is it because I'm trying to run it locally?

Once this is available, we should

- [ ] Update all references to APIs in the docs using this syntax

**Comment by lindalu-MSFT** [comment]
@twsouthwick I have no idea! You can go to the Learn support site [SiteHelp](https://sitehelp.microsoft.com/ ) and open a ticket. I'm sure they can help!
