### ISSUE TITLE
Incomplete example in "Delete text from a cell in a spreadsheet"

### ISSUE THREAD

**Issue by erezwanderman** [OfficeDev/open-xml-docs#20]
In the topic "[How to: Delete text from a cell in a spreadsheet document (Open XML SDK)](https://github.com/OfficeDev/open-xml-docs/blob/live/docs/how-to-delete-text-from-a-cell-in-a-spreadsheet.md)" there is a method called RemoveSharedStringItem, but it is not called.
I think a call to RemoveSharedStringItem should be added to DeleteTextFromCell.

**Comment by Linda-Editor** [comment]
@erezwanderman If you would like this change made, show me the exact spot you want this added and the exact string to include. Thank you.
