### ISSUE TITLE
Language dropdown

### ISSUE THREAD

**Issue by NextTurn** [OfficeDev/open-xml-docs#24]
Could you add a language dropdown menu so that C# and VB snippets won't show up at the same time?

![image](https://user-images.githubusercontent.com/45985406/56334076-7a519b00-61c9-11e9-9deb-4351ebed8a5e.png)

**Comment by Linda-Editor** [comment]
@NextTurn I'm not sure how to do that. Have you seen it somewhere else on docs.microsoft.com? If so, please send a link to the page. Thanks.

**Comment by NextTurn** [comment]
Here's an example https://docs.microsoft.com/dotnet/framework/interop/msgbox-sample

**Comment by Linda-Editor** [comment]
@NextTurn If you look in the API section, this functionality does exist there; for example: https://docs.microsoft.com/en-us/dotnet/api/documentformat.openxml.bibliography.abbreviatedcasenumber.localname?view=openxml-2.8.1

**Comment by NextTurn** [comment]
Yes, but could you make it apply to articles as well?

**Comment by Linda-Editor** [comment]
@NextTurn I'll look into it. Thanks for the suggestion.

@dmahugh - Doug, could you get this request to the right PM who can address it? Thanks...

**Comment by NextTurn** [comment]
The language selector dropdown menu is set in [docfx.json](https://github.com/OfficeDev/open-xml-docs/blob/master/docs/docfx.json).

See the following file for example

https://github.com/dotnet/dotnet-api-docs/blob/65c1594178155f1f1ddf00319ab3bbc9fe5bc01a/docfx.json#L133

**Comment by Linda-Editor** [comment]
@lindalu-MSFT can you follow up on this? It's about adding the language selector drop-down to conceptual topics in open-xml-docs. See the thread for more info. Thanks.

**Comment by lindalu-MSFT** [comment]
@davidchesnut Hi David, can I get your help with this? I updated the JSON, added:
`

"langs": {
--
  | "api/**.yml": ["csharp", "vb", "fsharp", "cpp"]
  | }
  | },

`

and ran it through the [JSON validator](https://jsonlint.com/) tool which came back as VALID. 

We need to add the drop-down language selector. Any idea what I'm doing wrong? I have a branch called lindalu-MSFT-add-lang [where I made the change](https://github.com/OfficeDev/open-xml-docs/blob/lindalu-MSFT-add-langs/docs/docfx.json).

**Comment by NextTurn** [comment]
@lindalu-MSFT Hi, please have a try with the following:

```json
"langs": {
  "**/*.yml": ["csharp", "vb"]
}
```

**Comment by lindalu-MSFT** [comment]
@NextTurn Did that do the trick? Sorry I lost track of this issue for a few days. I was out sick! :(

**Comment by NextTurn** [comment]
@lindalu-MSFT I guess that is correct. Can you verify it? Thanks!
