### ISSUE TITLE
Example code produce invalid format

### ISSUE THREAD

**Issue by jygarneau** [OfficeDev/open-xml-docs#56]
I'm trying your code example "CreateSpreadsheetWorkbook" for generating a simple spreadsheet and work fine (See "Text.xslx" attached). But when calling "InsertChartInSpreadsheet", the file is no more valid!

[Test.xlsx](https://github.com/OfficeDev/open-xml-docs/files/5354776/Test.xlsx)

**Comment by mikeebowen** [comment]
closed by
- #296
