### ISSUE TITLE
Invalid link to download Open XML SDK 2.5

### ISSUE THREAD

**Issue by ElizabethSamuel-MSFT** [OfficeDev/open-xml-docs#62]
This link is broken and shows up at least 20 times in this docset.
- https://www.microsoft.com/download/details.aspx?id=30425

Can you fix this issue?

The broken link was reported in our office-js documentation which we fixed by sending users to nuget.org ([related PR](https://github.com/OfficeDev/office-js-docs-pr/pull/2708/files)).

Thanks.

@tomjebo @twsouthwick @mikeebowen

**Comment by tomjebo** [comment]
adding @AlfredHellstern. The documentation is still referring to the 2.5 version so pointing to the up to date github version might still be misleading. But the github link is [https://github.com/OfficeDev/Open-XML-SDK](https://github.com/OfficeDev/Open-XML-SDK)

**Comment by lindalu-MSFT** [comment]
I fixed this via this PR:
https://github.com/OfficeDev/open-xml-docs/pull/72
