### ISSUE TITLE
TD in title

### ISSUE THREAD

**Issue by woeterman94** [OfficeDev/open-xml-docs#94]
![image](https://user-images.githubusercontent.com/5755057/156780530-7f67eebd-d1e2-4608-b82e-d542b69c1b5a.png)

https://docs.microsoft.com/en-us/office/open-xml/open-xml-sdk?redirectedfrom=MSDN

Under recommended content

[Getting started with the Open XML SDK 2.5 for Office</td>](https://docs.microsoft.com/en-us/office/open-xml/getting-started)

**Comment by lindalu-MSFT** [comment]
Cannot repro
